name = "telega"
version = "0.9.0"
description = "Gleam Telegram Bot Library"
licences = ["Apache-2.0"]
repository = { type = "github", user = "bondiano", repo = "telega-gleam" }
links = [
    { title = "Issues", href = "https://github.com/bondiano/telega-gleam/issues" },
    { title = "Examples", href = "https://github.com/bondiano/telega-gleam/tree/master/examples" },
]

[documentation]
pages = [
    { title = " ", path = "#", source = "" },
    { title = "Conversation", path="docs/conversation.html", source="docs/conversation.md" },
]

gleam = ">= 1.11.0"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 1.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_httpc = ">= 4.0.0 and < 5.0.0"
gleam_erlang = ">= 0.34.0 and < 1.0.0"
gleam_otp = ">= 0.16.0 and < 1.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"
gleam_time = ">= 1.2.0 and < 2.0.0"
logging = ">= 1.3.0 and < 2.0.0"
wisp = ">= 1.7.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.2.0 and < 2.0.0"
