name = "bot"
version = "1.0.0"
description = "A Telega Commands example"

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 1.0.0"
gleam_erlang = ">= 1.2.0 and < 2.0.0"
wisp = ">= 1.7.0 and < 2.0.0"
mist = ">= 5.0.0 and < 6.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
telega = { path = "../.." }
simplifile = ">= 2.3.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
