name = "restaurant_booking"
version = "1.0.0"
description = "Restaurant table booking bot with persistent flows"

[dependencies]
telega = { path = "../.." }
gleam_erlang = ">= 1.3.0 and < 2.0.0"
pog = ">= 4.1.0 and < 5.0.0"
gleam_stdlib = ">= 0.62.1 and < 1.0.0"
dot_env = ">= 1.2.0 and < 2.0.0"
wisp = ">= 1.8.0 and < 2.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
gleam_time = ">= 1.4.0 and < 2.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
logging = ">= 1.3.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
squirrel = ">= 4.4.1 and < 5.0.0"
