name = "bot"
version = "1.0.0"
description = "Telega Echo Bot example"

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 1.0.0"
gleam_erlang = ">= 1.2.0 and < 2.0.0"
wisp = ">= 1.7.0 and < 2.0.0"
mist = ">= 5.0.0 and < 6.0.0"
telega = { path = "../.." }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
