name = "bot"
version = "1.0.0"
description = "A Telega Echo Bot example"

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 1.0.0"
gleam_erlang = ">= 0.34.0 and < 1.0.0"
wisp = ">= 1.7.0 and < 2.0.0"
telega = { path = "../.." }
mist = ">= 4.0.4 and < 5.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
