name = "bot"
version = "1.0.0"
description = "Telega Echo Bot example with long polling"

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 1.0.0"
telega = { path = "../.." }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
