name = "bot"
version = "1.0.0"
description = "A Telega Session example"

[dependencies]
gleam_stdlib = ">= 0.52.0 and < 1.0.0"
mist = ">= 4.0.4 and < 5.0.0"
gleam_erlang = ">= 0.33.0 and < 1.0.0"
wisp = ">= 1.5.1 and < 2.0.0"
dotenv_gleam = ">= 1.0.7 and < 2.0.0"
telega = { path = "../.." }
carpenter = ">= 0.3.1 and < 1.0.0"
envoy = ">= 1.0.2 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
