//// Per-method facts derived from the Telegram Bot API spec.
////
//// The only fact so far is **idempotency**: whether replaying a method after a
//// transport error or a 5xx is safe. `telega/client`'s retry policy reads it,
//// so the list of methods that must not be retried is generated from the spec
//// and complete, instead of being guessed from a name prefix at runtime.
////
//// Generated by `task codegen` — do not edit.

import gleam/result

// This file is auto-generated for Bot API 10.3 from the Telegram Bot API spec.
// Do not edit — run `task codegen` to regenerate.

/// The Bot API version this table was generated from.
pub const bot_api_version = "Bot API 10.3"

/// How many methods the table covers.
pub const method_count = 185

/// Whether replaying `method` is safe, or `Error(Nil)` if this Bot API
/// version has no such method.
pub fn lookup_idempotent(method method: String) -> Result(Bool, Nil) {
  case method {
    "addStickerToSet" -> Ok(False)
    "answerCallbackQuery" -> Ok(True)
    "answerChatJoinRequestQuery" -> Ok(True)
    "answerGuestQuery" -> Ok(False)
    "answerInlineQuery" -> Ok(True)
    "answerPreCheckoutQuery" -> Ok(True)
    "answerShippingQuery" -> Ok(True)
    "answerWebAppQuery" -> Ok(False)
    "approveChatJoinRequest" -> Ok(True)
    "approveSuggestedPost" -> Ok(True)
    "banChatMember" -> Ok(True)
    "banChatSenderChat" -> Ok(True)
    "close" -> Ok(True)
    "closeForumTopic" -> Ok(True)
    "closeGeneralForumTopic" -> Ok(True)
    "convertGiftToStars" -> Ok(False)
    "copyMessage" -> Ok(False)
    "copyMessages" -> Ok(False)
    "createChatInviteLink" -> Ok(False)
    "createChatSubscriptionInviteLink" -> Ok(False)
    "createForumTopic" -> Ok(False)
    "createInvoiceLink" -> Ok(False)
    "createNewStickerSet" -> Ok(False)
    "declineChatJoinRequest" -> Ok(True)
    "declineSuggestedPost" -> Ok(True)
    "deleteAllMessageReactions" -> Ok(True)
    "deleteBusinessMessages" -> Ok(True)
    "deleteChatPhoto" -> Ok(True)
    "deleteChatStickerSet" -> Ok(True)
    "deleteEphemeralMessage" -> Ok(True)
    "deleteForumTopic" -> Ok(True)
    "deleteMessage" -> Ok(True)
    "deleteMessageReaction" -> Ok(True)
    "deleteMessages" -> Ok(True)
    "deleteMyCommands" -> Ok(True)
    "deleteStickerFromSet" -> Ok(True)
    "deleteStickerSet" -> Ok(True)
    "deleteStory" -> Ok(True)
    "deleteWebhook" -> Ok(True)
    "editChatInviteLink" -> Ok(True)
    "editChatSubscriptionInviteLink" -> Ok(True)
    "editEphemeralMessageCaption" -> Ok(True)
    "editEphemeralMessageMedia" -> Ok(True)
    "editEphemeralMessageReplyMarkup" -> Ok(True)
    "editEphemeralMessageText" -> Ok(True)
    "editForumTopic" -> Ok(True)
    "editGeneralForumTopic" -> Ok(True)
    "editMessageCaption" -> Ok(True)
    "editMessageChecklist" -> Ok(True)
    "editMessageLiveLocation" -> Ok(True)
    "editMessageMedia" -> Ok(True)
    "editMessageReplyMarkup" -> Ok(True)
    "editMessageText" -> Ok(True)
    "editStory" -> Ok(True)
    "editUserStarSubscription" -> Ok(True)
    "exportChatInviteLink" -> Ok(False)
    "forwardMessage" -> Ok(False)
    "forwardMessages" -> Ok(False)
    "getAvailableGifts" -> Ok(True)
    "getBusinessAccountGifts" -> Ok(True)
    "getBusinessAccountStarBalance" -> Ok(True)
    "getBusinessConnection" -> Ok(True)
    "getChat" -> Ok(True)
    "getChatAdministrators" -> Ok(True)
    "getChatGifts" -> Ok(True)
    "getChatMember" -> Ok(True)
    "getChatMemberCount" -> Ok(True)
    "getChatMenuButton" -> Ok(True)
    "getCustomEmojiStickers" -> Ok(True)
    "getFile" -> Ok(True)
    "getForumTopicIconStickers" -> Ok(True)
    "getGameHighScores" -> Ok(True)
    "getManagedBotAccessSettings" -> Ok(True)
    "getManagedBotToken" -> Ok(True)
    "getMe" -> Ok(True)
    "getMyCommands" -> Ok(True)
    "getMyDefaultAdministratorRights" -> Ok(True)
    "getMyDescription" -> Ok(True)
    "getMyName" -> Ok(True)
    "getMyShortDescription" -> Ok(True)
    "getMyStarBalance" -> Ok(True)
    "getStarTransactions" -> Ok(True)
    "getStickerSet" -> Ok(True)
    "getUpdates" -> Ok(True)
    "getUserChatBoosts" -> Ok(True)
    "getUserGifts" -> Ok(True)
    "getUserPersonalChatMessages" -> Ok(True)
    "getUserProfileAudios" -> Ok(True)
    "getUserProfilePhotos" -> Ok(True)
    "getWebhookInfo" -> Ok(True)
    "giftPremiumSubscription" -> Ok(False)
    "hideGeneralForumTopic" -> Ok(True)
    "leaveChat" -> Ok(True)
    "logOut" -> Ok(True)
    "pinChatMessage" -> Ok(True)
    "postStory" -> Ok(False)
    "promoteChatMember" -> Ok(True)
    "readBusinessMessage" -> Ok(True)
    "refundStarPayment" -> Ok(False)
    "removeBusinessAccountProfilePhoto" -> Ok(True)
    "removeChatVerification" -> Ok(True)
    "removeMyProfilePhoto" -> Ok(True)
    "removeUserVerification" -> Ok(True)
    "reopenForumTopic" -> Ok(True)
    "reopenGeneralForumTopic" -> Ok(True)
    "replaceManagedBotToken" -> Ok(False)
    "replaceStickerInSet" -> Ok(False)
    "repostStory" -> Ok(False)
    "restrictChatMember" -> Ok(True)
    "revokeChatInviteLink" -> Ok(True)
    "savePreparedInlineMessage" -> Ok(False)
    "savePreparedKeyboardButton" -> Ok(False)
    "sendAnimation" -> Ok(False)
    "sendAudio" -> Ok(False)
    "sendChatAction" -> Ok(True)
    "sendChatJoinRequestWebApp" -> Ok(False)
    "sendChecklist" -> Ok(False)
    "sendContact" -> Ok(False)
    "sendDice" -> Ok(False)
    "sendDocument" -> Ok(False)
    "sendGame" -> Ok(False)
    "sendGift" -> Ok(False)
    "sendInvoice" -> Ok(False)
    "sendLivePhoto" -> Ok(False)
    "sendLocation" -> Ok(False)
    "sendMediaGroup" -> Ok(False)
    "sendMessage" -> Ok(False)
    "sendMessageDraft" -> Ok(False)
    "sendPaidMedia" -> Ok(False)
    "sendPhoto" -> Ok(False)
    "sendPoll" -> Ok(False)
    "sendRichMessage" -> Ok(False)
    "sendRichMessageDraft" -> Ok(False)
    "sendSticker" -> Ok(False)
    "sendVenue" -> Ok(False)
    "sendVideo" -> Ok(False)
    "sendVideoNote" -> Ok(False)
    "sendVoice" -> Ok(False)
    "setBusinessAccountBio" -> Ok(True)
    "setBusinessAccountGiftSettings" -> Ok(True)
    "setBusinessAccountName" -> Ok(True)
    "setBusinessAccountProfilePhoto" -> Ok(True)
    "setBusinessAccountUsername" -> Ok(True)
    "setChatAdministratorCustomTitle" -> Ok(True)
    "setChatDescription" -> Ok(True)
    "setChatMemberTag" -> Ok(True)
    "setChatMenuButton" -> Ok(True)
    "setChatPermissions" -> Ok(True)
    "setChatPhoto" -> Ok(True)
    "setChatStickerSet" -> Ok(True)
    "setChatTitle" -> Ok(True)
    "setCustomEmojiStickerSetThumbnail" -> Ok(True)
    "setGameScore" -> Ok(True)
    "setManagedBotAccessSettings" -> Ok(True)
    "setMessageReaction" -> Ok(True)
    "setMyCommands" -> Ok(True)
    "setMyDefaultAdministratorRights" -> Ok(True)
    "setMyDescription" -> Ok(True)
    "setMyName" -> Ok(True)
    "setMyProfilePhoto" -> Ok(True)
    "setMyShortDescription" -> Ok(True)
    "setPassportDataErrors" -> Ok(True)
    "setStickerEmojiList" -> Ok(True)
    "setStickerKeywords" -> Ok(True)
    "setStickerMaskPosition" -> Ok(True)
    "setStickerPositionInSet" -> Ok(True)
    "setStickerSetThumbnail" -> Ok(True)
    "setStickerSetTitle" -> Ok(True)
    "setUserEmojiStatus" -> Ok(True)
    "setWebhook" -> Ok(True)
    "stopMessageLiveLocation" -> Ok(True)
    "stopPoll" -> Ok(True)
    "transferBusinessAccountStars" -> Ok(False)
    "transferGift" -> Ok(False)
    "unbanChatMember" -> Ok(True)
    "unbanChatSenderChat" -> Ok(True)
    "unhideGeneralForumTopic" -> Ok(True)
    "unpinAllChatMessages" -> Ok(True)
    "unpinAllForumTopicMessages" -> Ok(True)
    "unpinAllGeneralForumTopicMessages" -> Ok(True)
    "unpinChatMessage" -> Ok(True)
    "upgradeGift" -> Ok(False)
    "uploadStickerFile" -> Ok(False)
    "verifyChat" -> Ok(True)
    "verifyUser" -> Ok(True)
    _ -> Error(Nil)
  }
}

/// Whether replaying `method` after a failed attempt is safe.
///
/// A method this Bot API version does not know is treated as unsafe: a
/// custom or newer method is more likely to create something than not.
pub fn is_idempotent(method method: String) -> Bool {
  lookup_idempotent(method) |> result.unwrap(False)
}

/// Every method this Bot API version has, sorted by name.
pub fn methods() -> List(String) {
  [
    "addStickerToSet",
    "answerCallbackQuery",
    "answerChatJoinRequestQuery",
    "answerGuestQuery",
    "answerInlineQuery",
    "answerPreCheckoutQuery",
    "answerShippingQuery",
    "answerWebAppQuery",
    "approveChatJoinRequest",
    "approveSuggestedPost",
    "banChatMember",
    "banChatSenderChat",
    "close",
    "closeForumTopic",
    "closeGeneralForumTopic",
    "convertGiftToStars",
    "copyMessage",
    "copyMessages",
    "createChatInviteLink",
    "createChatSubscriptionInviteLink",
    "createForumTopic",
    "createInvoiceLink",
    "createNewStickerSet",
    "declineChatJoinRequest",
    "declineSuggestedPost",
    "deleteAllMessageReactions",
    "deleteBusinessMessages",
    "deleteChatPhoto",
    "deleteChatStickerSet",
    "deleteEphemeralMessage",
    "deleteForumTopic",
    "deleteMessage",
    "deleteMessageReaction",
    "deleteMessages",
    "deleteMyCommands",
    "deleteStickerFromSet",
    "deleteStickerSet",
    "deleteStory",
    "deleteWebhook",
    "editChatInviteLink",
    "editChatSubscriptionInviteLink",
    "editEphemeralMessageCaption",
    "editEphemeralMessageMedia",
    "editEphemeralMessageReplyMarkup",
    "editEphemeralMessageText",
    "editForumTopic",
    "editGeneralForumTopic",
    "editMessageCaption",
    "editMessageChecklist",
    "editMessageLiveLocation",
    "editMessageMedia",
    "editMessageReplyMarkup",
    "editMessageText",
    "editStory",
    "editUserStarSubscription",
    "exportChatInviteLink",
    "forwardMessage",
    "forwardMessages",
    "getAvailableGifts",
    "getBusinessAccountGifts",
    "getBusinessAccountStarBalance",
    "getBusinessConnection",
    "getChat",
    "getChatAdministrators",
    "getChatGifts",
    "getChatMember",
    "getChatMemberCount",
    "getChatMenuButton",
    "getCustomEmojiStickers",
    "getFile",
    "getForumTopicIconStickers",
    "getGameHighScores",
    "getManagedBotAccessSettings",
    "getManagedBotToken",
    "getMe",
    "getMyCommands",
    "getMyDefaultAdministratorRights",
    "getMyDescription",
    "getMyName",
    "getMyShortDescription",
    "getMyStarBalance",
    "getStarTransactions",
    "getStickerSet",
    "getUpdates",
    "getUserChatBoosts",
    "getUserGifts",
    "getUserPersonalChatMessages",
    "getUserProfileAudios",
    "getUserProfilePhotos",
    "getWebhookInfo",
    "giftPremiumSubscription",
    "hideGeneralForumTopic",
    "leaveChat",
    "logOut",
    "pinChatMessage",
    "postStory",
    "promoteChatMember",
    "readBusinessMessage",
    "refundStarPayment",
    "removeBusinessAccountProfilePhoto",
    "removeChatVerification",
    "removeMyProfilePhoto",
    "removeUserVerification",
    "reopenForumTopic",
    "reopenGeneralForumTopic",
    "replaceManagedBotToken",
    "replaceStickerInSet",
    "repostStory",
    "restrictChatMember",
    "revokeChatInviteLink",
    "savePreparedInlineMessage",
    "savePreparedKeyboardButton",
    "sendAnimation",
    "sendAudio",
    "sendChatAction",
    "sendChatJoinRequestWebApp",
    "sendChecklist",
    "sendContact",
    "sendDice",
    "sendDocument",
    "sendGame",
    "sendGift",
    "sendInvoice",
    "sendLivePhoto",
    "sendLocation",
    "sendMediaGroup",
    "sendMessage",
    "sendMessageDraft",
    "sendPaidMedia",
    "sendPhoto",
    "sendPoll",
    "sendRichMessage",
    "sendRichMessageDraft",
    "sendSticker",
    "sendVenue",
    "sendVideo",
    "sendVideoNote",
    "sendVoice",
    "setBusinessAccountBio",
    "setBusinessAccountGiftSettings",
    "setBusinessAccountName",
    "setBusinessAccountProfilePhoto",
    "setBusinessAccountUsername",
    "setChatAdministratorCustomTitle",
    "setChatDescription",
    "setChatMemberTag",
    "setChatMenuButton",
    "setChatPermissions",
    "setChatPhoto",
    "setChatStickerSet",
    "setChatTitle",
    "setCustomEmojiStickerSetThumbnail",
    "setGameScore",
    "setManagedBotAccessSettings",
    "setMessageReaction",
    "setMyCommands",
    "setMyDefaultAdministratorRights",
    "setMyDescription",
    "setMyName",
    "setMyProfilePhoto",
    "setMyShortDescription",
    "setPassportDataErrors",
    "setStickerEmojiList",
    "setStickerKeywords",
    "setStickerMaskPosition",
    "setStickerPositionInSet",
    "setStickerSetThumbnail",
    "setStickerSetTitle",
    "setUserEmojiStatus",
    "setWebhook",
    "stopMessageLiveLocation",
    "stopPoll",
    "transferBusinessAccountStars",
    "transferGift",
    "unbanChatMember",
    "unbanChatSenderChat",
    "unhideGeneralForumTopic",
    "unpinAllChatMessages",
    "unpinAllForumTopicMessages",
    "unpinAllGeneralForumTopicMessages",
    "unpinChatMessage",
    "upgradeGift",
    "uploadStickerFile",
    "verifyChat",
    "verifyUser",
  ]
}

/// Whether `method` is a method of this Bot API version.
pub fn is_method(method method: String) -> Bool {
  lookup_idempotent(method) |> result.is_ok
}
