//// Per-update-kind facts derived from the Telegram Bot API spec.
////
//// The optional fields of the spec's `Update` type are three things at once:
//// the names Telegram accepts in `allowed_updates`, the payloads
//// `telega/update` has to dispatch on, and the kinds a router can ask for. All
//// of them come from this one table, so an update kind cannot be half-known.
////
//// Generated by `task codegen` — do not edit.

// This file is auto-generated for Bot API 10.3 from the Telegram Bot API spec.
// Do not edit — run `task codegen` to regenerate.

/// The Bot API version this table was generated from.
pub const bot_api_version = "Bot API 10.3"

/// How many update kinds this Bot API version has.
pub const update_kind_count = 27

/// Every optional field of the spec's `Update` type, in spec order —
/// exactly the names Telegram accepts in `allowed_updates`.
pub fn update_fields() -> List(String) {
  [
    "message",
    "edited_message",
    "channel_post",
    "edited_channel_post",
    "business_connection",
    "business_message",
    "edited_business_message",
    "deleted_business_messages",
    "guest_message",
    "message_reaction",
    "message_reaction_count",
    "inline_query",
    "chosen_inline_result",
    "callback_query",
    "shipping_query",
    "pre_checkout_query",
    "purchased_paid_media",
    "poll",
    "poll_answer",
    "my_chat_member",
    "chat_member",
    "chat_join_request",
    "chat_boost",
    "removed_chat_boost",
    "managed_bot",
    "subscription",
    "stopped_message_generation",
  ]
}

/// Whether `name` is an update kind this Bot API version knows, i.e. a
/// name Telegram accepts in `allowed_updates`.
pub fn is_update_field(name name: String) -> Bool {
  case name {
    "message" -> True
    "edited_message" -> True
    "channel_post" -> True
    "edited_channel_post" -> True
    "business_connection" -> True
    "business_message" -> True
    "edited_business_message" -> True
    "deleted_business_messages" -> True
    "guest_message" -> True
    "message_reaction" -> True
    "message_reaction_count" -> True
    "inline_query" -> True
    "chosen_inline_result" -> True
    "callback_query" -> True
    "shipping_query" -> True
    "pre_checkout_query" -> True
    "purchased_paid_media" -> True
    "poll" -> True
    "poll_answer" -> True
    "my_chat_member" -> True
    "chat_member" -> True
    "chat_join_request" -> True
    "chat_boost" -> True
    "removed_chat_boost" -> True
    "managed_bot" -> True
    "subscription" -> True
    "stopped_message_generation" -> True
    _ -> False
  }
}

/// The spec type an update field carries (`"message"` -> `"Message"`),
/// or `Error(Nil)` for a name this Bot API version does not know.
pub fn update_field_type(field field: String) -> Result(String, Nil) {
  case field {
    "message" -> Ok("Message")
    "edited_message" -> Ok("Message")
    "channel_post" -> Ok("Message")
    "edited_channel_post" -> Ok("Message")
    "business_connection" -> Ok("BusinessConnection")
    "business_message" -> Ok("Message")
    "edited_business_message" -> Ok("Message")
    "deleted_business_messages" -> Ok("BusinessMessagesDeleted")
    "guest_message" -> Ok("Message")
    "message_reaction" -> Ok("MessageReactionUpdated")
    "message_reaction_count" -> Ok("MessageReactionCountUpdated")
    "inline_query" -> Ok("InlineQuery")
    "chosen_inline_result" -> Ok("ChosenInlineResult")
    "callback_query" -> Ok("CallbackQuery")
    "shipping_query" -> Ok("ShippingQuery")
    "pre_checkout_query" -> Ok("PreCheckoutQuery")
    "purchased_paid_media" -> Ok("PaidMediaPurchased")
    "poll" -> Ok("Poll")
    "poll_answer" -> Ok("PollAnswer")
    "my_chat_member" -> Ok("ChatMemberUpdated")
    "chat_member" -> Ok("ChatMemberUpdated")
    "chat_join_request" -> Ok("ChatJoinRequest")
    "chat_boost" -> Ok("ChatBoostUpdated")
    "removed_chat_boost" -> Ok("ChatBoostRemoved")
    "managed_bot" -> Ok("ManagedBotUpdated")
    "subscription" -> Ok("BotSubscriptionUpdated")
    "stopped_message_generation" -> Ok("MessageGenerationStopped")
    _ -> Error(Nil)
  }
}
