name: check

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 28.0.1
          gleam-version: 1.15.1
          rebar3-version: 3.25.1

      - name: Install Dependencies
        run: gleam deps download

      - name: Check Format
        run: gleam format --check src test

      - name: Check
        run: gleam check

      - name: Test
        run: GLEAM_LOG=trace gleam test

      # - name: Check Examples
      #   run: |
      #     for dir in examples/*/; do
      #       echo "=== Checking $dir ==="
      #       cd "$dir"
      #       gleam deps download
      #       gleam format --check src test
      #       gleam check
      #       gleam test
      #       cd "$GITHUB_WORKSPACE"
      #     done
