name: check

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 28.0.1
          gleam-version: 1.12.0
          rebar3-version: 3.25.1

      - name: Install Dependencies
        run: gleam deps download

      - name: Check Format
        run: gleam format --check src test

      - name: Test
        run: gleam test
