name: check

on:
  push:
    branches:
      - master
      - main
  pull_request:

env:
  # Increase inline size limit to avoid compilation hangs with deeply nested functions
  # Default is 24, we use 5 to handle Gleam's deeply nested use expressions
  # See: https://github.com/gleam-lang/gleam/issues/4287
  ERL_COMPILER_OPTIONS: '[{inline_size, 5}]'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 28.0.1
          gleam-version: 1.12.0
          rebar3-version: 3.25.1

      - name: Install Dependencies
        run: gleam deps download

      - name: Check Format
        run: gleam format --check src test

      - name: Test
        run: GLEAM_LOG=trace gleam test
